### PR TITLE
70 shiny base

### PR DESCRIPTION
**Pull request by drBosse**

### CODE REVIEW

**Comment by drBosse** [comment]
tried to swap building verifa/tempor with verifa/shiny-base

but I do not really get it, since I can not see `tempor` in ghcr
have access and can see other verifa images

**Comment by mike-vainio-verifa** [comment]
> tried to swap building verifa/tempor with verifa/shiny-base
> 
> but I do not really get it, since I can not see `tempor` in ghcr have access and can see other verifa images

The shiny image seems to build in seconds when I tested it, we could just remove the whole image building from this repo. I mostly wanted to add it initial since it took so long to build a base. What do you think? It's smooth with the Makefile for the build, I just called make in the private repo to build the image.

**Comment by drBosse** [comment]
I think we can keep just make if buildtime is OK

**Comment by mike-vainio-verifa** [comment]
#72 I opened a PR to remove the workflow

**Pull request closed without merging**
